version: '3'
networks:
  cassandra:
volumes:
  cassandra-three:
services:
  cassandra-three:
    image: cassandra:4.0.11
    container_name: cassandra-three
    hostname: cassandra-three
    mem_limit: 1g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - cassandra-three:/var/lib/cassandra
      # - ./etc/cassandra-three:/etc/cassandra   # Use your own config files for full control
    environment:
        CASSANDRA_SEEDS: ${CASSANDRA_ONE_IP}
        CASSANDRA_BROADCAST_ADDRESS: ${CASSANDRA_THREE_IP}
        CASSANDRA_CLUSTER_NAME: Universe
        CASSANDRA_DC: Earth
        CASSANDRA_RACK: Asia
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
        # MAX_HEAP_SIZE: 1G
