version: '3'
networks:
  cassandra:
volumes:
  cassandra-one:
services:
  cassandra-one:
    image: cassandra:4.0.11
    container_name: cassandra-one
    hostname: cassandra-one
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - cassandra-one:/var/lib/cassandra
      # - ./etc/cassandra-one:/etc/cassandra   # Use your own config files for full control
    environment:
      MAX_HEAP_SIZE: 2g
      HEAP_NEWSIZE: 1g
      CASSANDRA_SEEDS: cassandra-one
      CASSANDRA_CLUSTER_NAME: Universe
      CASSANDRA_DC: Earth
      CASSANDRA_RACK: Asia
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      # MAX_HEAP_SIZE: 1G